MoSDeF_dihedral_fit/__init__.py
MoSDeF_dihedral_fit/dihedral_fit/fit_dihedral_with_gomc.py
MoSDeF_dihedral_fit/tests/README.md
MoSDeF_dihedral_fit/utils/basic_operations.py
MoSDeF_dihedral_fit/utils/file_read_and_write.py
MoSDeF_dihedral_fit/utils/math_operations.py

The initial files which are required to fit the dihedral.

The initial files which are required to fit the dihedral.  

---

CITATION.cff
Dockerfile
MANIFEST.in
codecov.yml
devtools/docker-entrypoint.sh
setup.cfg
setup.py

added setup file and enviroment files

added setup files and enviroment files

---

environment.yml
mosdef_dihedral_fit/dihedral_fit/fit_dihedral_with_gomc.py
mosdef_dihedral_fit/utils/basic_operations.py
mosdef_dihedral_fit/utils/file_read_and_write.py

add python vmd package and change os.waitpid to os.wait4 to be compatible with Mac

add python vmd package and change os.waitpid to os.wait4 to be compatible with Mac

---

mosdef_dihedral_fit/dihedral_fit/fit_dihedral_with_gomc.py
mosdef_dihedral_fit/utils/file_read_and_write.py

fixed bug in the fit_dihedral and file_read_and_write that was double printing dihedral constants if not set to 0 in xml file

fixed bug in the fit_dihedral and file_read_and_write that was double printing dihedral constants if not set to 0 in xml file

---

mosdef_dihedral_fit/tests/test_math_operation.py
mosdef_dihedral_fit/utils/math_operations.py

added test_math_operations.py.  Not completed, but added from top of math_operations.py to and including the dihedral angle.

added test_math_operations.py.  Not completed, but added from top of math_operations.py to and including the dihedral angle.

---

mosdef_dihedral_fit/dihedral_fit/fit_dihedral_with_gomc.py
mosdef_dihedral_fit/utils/file_read_and_write.py

updated docs to have no warning and look better.

updated docs to have no warning and look better.

---

docs/getting_started/installation/installation.rst
docs/getting_started/quick_start/quick_start.rst
docs/index.rst
docs/overview/general_info.rst
docs/reference/citing_mosdef_dihedral_fit_python.rst
docs/reference/credits.rst
mosdef_dihedral_fit/dihedral_fit/fit_dihedral_with_gomc.py
mosdef_dihedral_fit/tests/test_fit_dihedral_with_gomc.py
mosdef_dihedral_fit/utils/file_read_and_write.py
mosdef_dihedral_fit/utils/io.py

Added unit tests for user input and other checks.  
Added Guasian 16 and GOMC >=2.75 compatible.

Added unit tests for user input and other checks.

---

Dockerfile

Fix the failing docker build in main. Address #28.

Fix Dockerfile 

---

docs/index.rst
docs/overview/general_info.rst

Added dihedral equations (OPLS, RB, and Periodic) to docs

added dihedral equations to docs

---

docs/getting_started/quick_start/quick_start.rst
docs/topic_guides/data_structures.rst
mosdef_dihedral_fit/__init__.py

- Added the dihedral angle calculation to the documentation.
- Added the dihedral angle function to the __init__.py file

add the dihedral angle calculation to the Doc 

---

paper/paper.md

added chris's orchid to paper.md

added chris's orchid

---

.github/workflows/CI.yml
mosdef_dihedral_fit/tests/test_fit_dihedral_with_gomc.py

Added the GOMC docker image to the CI.yml file, so GOMC can be used in the automated tests.

adding the GOMC docker image to the CI.yml file

---

paper/paper.md

added spaces int he paper.md equations so it reads on GitHub Properly

added spaces int he paper.md equations so it reads on GitHub Properly

---

README.md
setup.py

- added the link to the docs webpage
- updated the license reference

added the link to the docs webpage and updated the license reference.

---

docs/reference/credits.rst
paper/paper.md

changed company name to only Atomfold

changed company name to only Atomfold

---

mosdef_dihedral_fit/tests/test_file_read_write.py

changed assert condition in test_file_read_write.py

changed assert condition in test_file_read_write.py

---

Dockerfile

modified dockerfile to get docker working 
_**Old command:**_
RUN apk update && apk add libarchive
**_New command:_**
RUN apt-get update \
&& apt-get install -y wget pip
RUN apt-get install -y libarchive13

modified dockerfile

---

Dockerfile

removed duplicate nomkl in mamba env create nomkl --file environment.yml in the Dockerfile
This is trying to fix the Docker build error

removed duplicate nomkl in mamba env create nomkl --file environment.yml in the Dockerfile

---

docs/index.rst
docs/overview/general_info.rst
paper/paper.bib

added paper bib references and info in the docs on how to setup UA force fields with these AA QM data

added paper bib references and info in the docs on how to setup UA force fields with these AA QM data

---

.github/workflows/CI.yml
README.md

Add CI test status badge and pre-commit status badge to README.md. Pause docker build on main until we can add username and password to repo secret.

Pause Docker Build

---

mosdef_dihedral_fit/__init__.py

changed the git __init__.py file error as it is failing on conda-forge.  It was a bug that did not fail until Conda-forge

changed the git __init__.py file error

---

docs/environment_docs.yml
docs/getting_started/installation/installation.rst
environment.yml

fixed the locked python versions to 3.11.xxx in env.yml files not at 3.11.0

fixed the locked python versions to 3.11.xxx in yml files 

---

.github/workflows/CI.yml

made /mosdef-dihedral-fit lowercase in docker tags, as it said to do this in the docker build error.

made /mosdef-dihedral-fit lowercase in docker tags

---

README.md

fix readme periodic eqn typo

---

.github/workflows/CI.yml
LICENSE

fix unit tests

---

docs/index.rst
docs/overview/general_info.rst

Changed the wording on:
-  How to use the periodic form for CHARMM 
- Equations only go to 4th cos power/multiple.

Changed the wording on periodic form for CHARMM and equation math coverage. 

---

paper/paper.bib

added the gmso and ff-utils zenodo DOIs

added the gmso and ff-utils zenodo DOIs

---

paper/paper.bib

Removed duplicate citation for JOSS publication

Removed duplicate citation for JOSS publication
